# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"
x = s.split()
print(x)


['Hi', 'there', 'Sam!']


In [1]:
s = "Hi there sam!"
x = s.split()
print(x)

['Hi', 'there', 'sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [6]:
s = "The diameter of Earth is {diameter:} kilometers."
print(s.format(diameter = 12742))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [8]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [10]:
import numpy as np
array = np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
import numpy as np
array = np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [12]:
import numpy as np
array = np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
import numpy as np
x = np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [17]:
import pandas as pd
data = {'Name':['Murugeshan','Manoj','Naveesh'],'Age': [20,21,20]}
df = pd.DataFrame(data)
df


Name  Age
0  Murugeshan   20
1       Manoj   21
2     Naveesh   20

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [24]:
import datetime
import pandas as pd
start = datetime.datetime.strptime("01-01-2023", "%d-%m-%Y")
end = datetime.datetime.strptime("10-02-2023", "%d-%m-%Y")
dategenerated = pd.date_range(start, end)
print (dategenerated. strftime("%d-%m-%y"))                        

Index(['01-01-23', '02-01-23', '03-01-23', '04-01-23', '05-01-23', '06-01-23',
       '07-01-23', '08-01-23', '09-01-23', '10-01-23', '11-01-23', '12-01-23',
       '13-01-23', '14-01-23', '15-01-23', '16-01-23', '17-01-23', '18-01-23',
       '19-01-23', '20-01-23', '21-01-23', '22-01-23', '23-01-23', '24-01-23',
       '25-01-23', '26-01-23', '27-01-23', '28-01-23', '29-01-23', '30-01-23',
       '31-01-23', '01-02-23', '02-02-23', '03-02-23', '04-02-23', '05-02-23',
       '06-02-23', '07-02-23', '08-02-23', '09-02-23', '10-02-23'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [21]:
import pandas as pd
data = [['aaa',22],['bbb',25],['ccc',24]]
df = pd.DataFrame(data,columns =['Name','Age'])
df

Name  Age
0  aaa   22
1  bbb   25
2  ccc   24